baseURL = 'https://holtonma.github.io/'
languageCode = 'en-us'
title = 'Mark Holton - Hands on Software Architect'
theme = 'PaperMod'
googleAnalytics = 'G-3VHWR9KEC4'

[params]
env = "production"
title = "Mark Holton"
description = "A blog about software development and technology"
keywords = ["software", "development", "technology", "programming"]
author = "Mark Holton"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
safari_pinned_tab = "/safari-pinned-tab.svg"

[params.label]
text = "Mark Holton"
icon = "/apple-touch-icon.png"
iconHeight = 35

[params.profileMode]
enabled = false
title = "Mark Holton"
subtitle = "Software Developer"
imageUrl = "/profile.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "Mark Holton"

[[params.socialIcons]]
name = "github"
url = "https://github.com/holtonma"

[params.social]
twitter = "markholton"

[params.analytics.google]
SiteVerificationTag = "fcAcxqVg1WFL-6SaeDOdfqEaJhetod2dh8EmNNSaKGQ"
id = "G-3VHWR9KEC4"

# [params.analytics.bing]
# SiteVerificationTag = "XYZabc"

# [params.analytics.yandex]
# SiteVerificationTag = "XYZabc"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

[params.editPost]
URL = "https://github.com/holtonma/holtonma.github.io/tree/main/content"
Text = "Suggest Changes"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 25

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 40

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNos = false
style = "github"

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]

[sitemap]
changeFreq = "weekly"
priority = 0.8
filename = "sitemap.xml"
